---
- hosts: all
  become: yes
  become_user: root

  tasks:
  - name: update
    apt: upgrade=yes

  - name: Install packages
    apt: pkg={{item}}
    with_items:
        - openjdk-11-jdk
        
  - name: Copy Hadoop
    copy:
      src: /var/lib/jenkins/workspace/hadoop-build/hadoop-dist/target/hadoop-3.1.4.tar.gz
      dest: /opt/

  - name: Unpack Hadoop
    unarchive:
      src: /opt/hadoop-3.1.4.tar.gz
      dest: /opt
      creates: /opt/hadoop-3.1.4
      copy: no
      owner: user
      group: user

  - name: hadoop current version link
    file: path=/opt/hadoop src=/opt/hadoop-3.1.4 state=link owner=user group=user
    
  - name: hadoop config files
    copy: dest=/opt/hadoop/etc/hadoop/{{item}} src=files/{{item}} mode=0644 owner=user group=user
    with_items:
        - hadoop-env.sh
        - core-site.xml
        - hdfs-site.xml

  - name: hadoop java activation
    copy: dest=/opt/hadoop/share/hadoop/common/activation-1.1.1.jar src=files/activation-1.1.1.jar mode=0644 owner=user group=user

  - name: hadoop format namenode
    command: /opt/hadoop/bin/hdfs namenode -format
    become: yes
    become_user: root

  - name: Starting Hadoop Single Cluster
    command: /opt/hadoop/sbin/start-dfs.sh
    become: yes
    become_user: root
